stackName: sdoneks
modelBucketArn: arn:aws:s3:::dummy-bucket
APIGW:
  stageName: dev
  throttle:
    rateLimit: 30
    burstLimit: 50
modelsRuntime:
- name: sdruntime
  namespace: default
  modelFilename: v1-5-pruned-emaonly.safetensors
  dynamicModel: false
  type: sdwebui
  extraValues:
    karpenter:
      nodeTemplate:
        amiFamily: Bottlerocket
      provisioner:
        instanceType:
        - g5.xlarge
        - g5.2xlarge
        capacityType:
          onDemand: true
          spot: true
    runtime:
      scaling:
        queueLength: 10
        minReplicaCount: 0
        cooldownPeriod: 300
