stackName: "SdOnEKS"
modelBucketArn: 'arn:aws-cn:s3:::sd-on-eks-model'
modelsRuntime:
- name: "sdruntime"
  namespace: "default"
  type: "SDWebUI"
  modelFilename: "v1-5-pruned-emaonly.safetensors"
  extraValues:
    karpenter:
      # nodeTemplate:
      #   amiFamily: Bottlerocket
      #   dataVolume:
      #     volumeSize: 80Gi
      #     volumeType: gp3
      #     deleteOnTermination: true
      #     iops: 4000
      #     throughput: 1000
      #     snapshotID: snap-0c122affcfefdb655 # EBS Snapshot ID with format snap-<snapshotid>
      provisioner:
        instanceType:
        - "g4dn.xlarge"
        capacityType:
          onDemand: true
          spot: false
    sdWebuiInferenceApi:
      inferenceApi:
        image:
          repository: 576159396516.dkr.ecr.cn-north-1.amazonaws.com.cn/huiyoujia/inference-api # Image Repository of stable diffusion runtime.
          tag: 30
      queueAgent:
        image:
          repository: 576159396516.dkr.ecr.cn-north-1.amazonaws.com.cn/huiyoujia/queue-agent # Image Repository of queue agent.
          tag: 8
      persistence:
        enabled: true
        existingClaim: "efs-model-storage-pvc"
      scaling:
        queueLength: 5 # Target value for queue length. One new instance will be launched when queue launch reaches the value.
        minReplicaCount: 0 # Minimum number of replicas of SD Runtime.
        maxReplicaCount: 5 # Maxinum number of replicas of SD Runtime.
        cooldownPeriod: 1200 # The period (in seconds) to wait after the last message before scaling down.
dynamicModelRuntime:
  enabled: false
  namespace: "default"
  extraValues:
    karpenter:
      provisioner:
        instanceType:
        - "g4dn.xlarge"
        - "g4dn.2xlarge"
        capacityType:
          onDemand: true
          spot: true
    sdWebuiInferenceApi:
      inferenceApi:
        image:
          repository: 576159396516.dkr.ecr.cn-north-1.amazonaws.com.cn/sd-on-eks/inference-api # Image Repository of stable diffusion runtime.
          tag: latest
      queueAgent:
        image:
          repository: 576159396516.dkr.ecr.cn-north-1.amazonaws.com.cn/sd-on-eks/queue-agent # Image Repository of queue agent.
          tag: latest
      persistence:
        enabled: true
        existingClaim: "efs-model-storage-pvc"
      scaling:
        queueLength: 20 # Target value for queue length. One new instance will be launched when queue launch reaches the value.
        minReplicaCount: 1 # Minimum number of replicas of SD Runtime.
        maxReplicaCount: 5 # Maxinum number of replicas of SD Runtime.
        cooldownPeriod: 300 # The period (in seconds) to wait after the last message before scaling down.