stackName: "SdOnEKS"
modelBucketArn: 'arn:aws-cn:s3:::sd-on-eks-model'
modelsRuntime:
- name: "sdruntime"
  namespace: "default"
  type: "SDWebUI"
  modelFilename: "v1-5-pruned-emaonly.safetensors"
  extraValues:
    karpenter:
      provisioner:
        instanceType:
        - "g4dn.xlarge"
        capacityType:
          onDemand: true
          spot: false
    sdWebuiInferenceApi:
      inferenceApi:
        image:
          repository: 576159396516.dkr.ecr.cn-north-1.amazonaws.com.cn/huiyoujia/inference-api # Image Repository of stable diffusion runtime.
          tag: 43
      queueAgent:
        image:
          repository: 576159396516.dkr.ecr.cn-north-1.amazonaws.com.cn/huiyoujia/queue-agent # Image Repository of queue agent.
          tag: 9
      persistence:
        enabled: true
        existingClaim: "efs-model-storage-pvc"
      scaling:
        queueLength: 5 # Target value for queue length. One new instance will be launched when queue launch reaches the value.
        minReplicaCount: 0 # Minimum number of replicas of SD Runtime.
        maxReplicaCount: 5 # Maxinum number of replicas of SD Runtime.
        cooldownPeriod: 1200 # The period (in seconds) to wait after the last message before scaling down.
- name: "inpaint-sdruntime"
  namespace: "default"
  type: "SDWebUI"
  modelFilename: "inpaint"
  extraValues:
    karpenter:
      provisioner:
        instanceType:
        - "g4dn.xlarge"
        capacityType:
          onDemand: true
          spot: false
    sdWebuiInferenceApi:
      inferenceApi:
        image:
          repository: 576159396516.dkr.ecr.cn-north-1.amazonaws.com.cn/huiyoujia/inpaint-api # Image Repository of stable diffusion runtime.
          tag: 15
      queueAgent:
        image:
          repository: 576159396516.dkr.ecr.cn-north-1.amazonaws.com.cn/huiyoujia/inpaint-queue-agent # Image Repository of queue agent.
          tag: 1
      persistence:
        enabled: true
        existingClaim: "efs-model-storage-pvc"
      scaling:
        queueLength: 15 # Target value for queue length. One new instance will be launched when queue launch reaches the value.
        minReplicaCount: 0 # Minimum number of replicas of SD Runtime.
        maxReplicaCount: 5 # Maxinum number of replicas of SD Runtime.
        cooldownPeriod: 1200 # The period (in seconds) to wait after the last message before scaling down.
- name: "sdxl-sdruntime"
  namespace: "default"
  type: "SDWebUI"
  modelFilename: "sdxl"
  extraValues:
    karpenter:
      provisioner:
        instanceType:
        - "g5.xlarge"
        capacityType:
          onDemand: true
          spot: false
    sdWebuiInferenceApi:
      inferenceApi:
        image:
          repository: 576159396516.dkr.ecr.cn-north-1.amazonaws.com.cn/huiyoujia/sdxl-api # Image Repository of stable diffusion runtime.
          tag: 7
      queueAgent:
        image:
          repository: 576159396516.dkr.ecr.cn-north-1.amazonaws.com.cn/huiyoujia/sdxl-queue-agent # Image Repository of queue agent.
          tag: 1
      persistence:
        enabled: true
        existingClaim: "efs-model-storage-pvc"
      scaling:
        queueLength: 5 # Target value for queue length. One new instance will be launched when queue launch reaches the value.
        minReplicaCount: 0 # Minimum number of replicas of SD Runtime.
        maxReplicaCount: 5 # Maxinum number of replicas of SD Runtime.
        cooldownPeriod: 1200 # The period (in seconds) to wait after the last message before scaling down.
- name: "sdxl-img2img-sdruntime"
  namespace: "default"
  type: "SDWebUI"
  modelFilename: "sdxl-img2img"
  extraValues:
    karpenter:
      provisioner:
        instanceType:
        - "g5.xlarge"
        capacityType:
          onDemand: true
          spot: false
    sdWebuiInferenceApi:
      inferenceApi:
        image:
          repository: 576159396516.dkr.ecr.cn-north-1.amazonaws.com.cn/huiyoujia/sdxl-img2img-api # Image Repository of stable diffusion runtime.
          tag: 1
      queueAgent:
        image:
          repository: 576159396516.dkr.ecr.cn-north-1.amazonaws.com.cn/huiyoujia/sdxl-queue-agent # Image Repository of queue agent.
          tag: 1
      persistence:
        enabled: true
        existingClaim: "efs-model-storage-pvc"
      scaling:
        queueLength: 5 # Target value for queue length. One new instance will be launched when queue launch reaches the value.
        minReplicaCount: 0 # Minimum number of replicas of SD Runtime.
        maxReplicaCount: 5 # Maxinum number of replicas of SD Runtime.
        cooldownPeriod: 1200 # The period (in seconds) to wait after the last message before scaling down.
dynamicModelRuntime:
  enabled: false
  namespace: "default"
  extraValues:
    karpenter:
      provisioner:
        instanceType:
        - "g4dn.xlarge"
        - "g4dn.2xlarge"
        capacityType:
          onDemand: true
          spot: true
    sdWebuiInferenceApi:
      inferenceApi:
        image:
          repository: 576159396516.dkr.ecr.cn-north-1.amazonaws.com.cn/sd-on-eks/inference-api # Image Repository of stable diffusion runtime.
          tag: latest
      queueAgent:
        image:
          repository: 576159396516.dkr.ecr.cn-north-1.amazonaws.com.cn/sd-on-eks/queue-agent # Image Repository of queue agent.
          tag: latest
      persistence:
        enabled: true
        existingClaim: "efs-model-storage-pvc"
      scaling:
        queueLength: 10 # Target value for queue length. One new instance will be launched when queue launch reaches the value.
        minReplicaCount: 1 # Minimum number of replicas of SD Runtime.
        maxReplicaCount: 5 # Maxinum number of replicas of SD Runtime.
        cooldownPeriod: 300 # The period (in seconds) to wait after the last message before scaling down.